name: Build Debug APKs

on:
  push:
    branches: ["**"]  # All branches
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x SubaruStart_Wear/gradlew

      - name: Build Phone APK (mobile)
        working-directory: SubaruStart_Wear
        run: ./gradlew :mobile:assembleDebug

      - name: Build Wear APK (wear)
        working-directory: SubaruStart_Wear
        run: ./gradlew :wear:assembleDebug

      - name: Upload Phone APK
        uses: actions/upload-artifact@v4
        with:
          name: phone-debug-apk
          path: SubaruStart_Wear/mobile/build/outputs/apk/debug/*.apk

      - name: Upload Wear APK
        uses: actions/upload-artifact@v4
        with:
          name: wear-debug-apk
          path: SubaruStart_Wear/wear/build/outputs/apk/debug/*.apk
