name: Build Phone and Wear APKs

on:
  push:
    branches: ["**"]  # Run on all branches

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: SubaruStart_Wear  

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'  

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build phone app (debug)
        run: ./gradlew :app:assembleDebug

      - name: Build wear app (debug)
        run: ./gradlew :wear:assembleDebug

      - name: Upload Phone APK
        uses: actions/upload-artifact@v4
        with:
          name: phone-debug-apk
          path: SubaruStart_Wear/app/build/outputs/apk/debug/app-debug.apk

      - name: Upload Wear APK
        uses: actions/upload-artifact@v4
        with:
          name: wear-debug-apk
          path: SubaruStart_Wear/wear/build/outputs/apk/debug/wear-debug.apk
